AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Umbrella template for all stacks in the application

Resources:
    DataResources:
      Type: AWS::Serverless::Application
      Properties:
        Location: ./data-resources/template.yaml

    SageMakerResources:
      Type: AWS::Serverless::Application
      Properties:
        Location: ./sagemaker-resources/template.yaml
      Parameters:
        WhisperModelImageRepositoryUri: !GetAtt WhisperImage.Outputs.WhisperModelImageRepositoryUri
        WhisperModelImageRepositoryArn: !GetAtt WhisperImage.Outputs.WhisperModelImageRepositoryArn
      DependsOn:
        - DataResources

    EpisodeDownloader:
      Type: AWS::Serverless::Application
      Properties:
        Location: ./episode-downloader/template.yaml
      DependsOn: DataResources