AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - SlicWatch-v2

Description: >
  episode-downloader

  Audio episode downloading from Anchor

Globals:
  Function:
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_METRICS_NAMESPACE: !Ref AWS::StackName
  Api:
    TracingEnabled: True

Parameters:
  PodcastRssUrl:
    Type: String
    Default: https://anchor.fm/s/6a3312a0/podcast/rss

Resources:
  TranscriptionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/transcription-step-function.asl.json
      DefinitionSubstitutions:
        AudioDownloaderFunctionArn: !GetAtt AudioDownloaderFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref AudioDownloaderFunction

  AudioDownloaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handleEvent
      Runtime: nodejs16.x
      Timeout: 900
      Environment:
        Variables:
          PODCAST_RSS_URL: !Ref PodcastRssUrl
          BUCKET_NAME: !Sub 'podwhisperer-${AWS::AccountId}-${AWS::Region}'
          POWERTOOLS_SERVICE_NAME: AudioDownloader
      Architectures:
        - arm64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/audio-downloader/app.js

Outputs:
  StateMachineArn:
    Value: !Ref TranscriptionStateMachine
